package ursus_test

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/advenn/ursus"
	"github.com/advenn/ursus/dtype"
	"github.com/advenn/ursus/internal/uerr"
	"github.com/advenn/ursus/ursustest"
)

func writeFile(t *testing.T, name, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

const salesCSV = `region,rep,amount,qty,active
eu,ann,10.5,1,true
us,bob,20.0,2,false
eu,cat,,3,true
apac,dan,40.25,4,false
`

// TestScanCSVInfersTypes checks the inference lattice end to end. Getting this
// wrong is not a crash — it is a String column where a number was wanted, and the
// user finding out three operations later.
func TestScanCSVInfersTypes(t *testing.T) {
	df, err := ursus.ScanCSV(writeFile(t, "sales.csv", salesCSV)).
		Collect(t.Context(), ursus.WithVerify())
	if err != nil {
		t.Fatal(err)
	}

	want := []dtype.DataType{dtype.String, dtype.String, dtype.Float64, dtype.Int64, dtype.Bool}
	for i, w := range want {
		if got := df.Schema().Field(i).Type; got != w {
			t.Errorf("column %q inferred as %s, want %s",
				df.Schema().Field(i).Name, got, w)
		}
	}
	if df.Height() != 4 {
		t.Errorf("got %d rows, want 4\n%s", df.Height(), df)
	}
	// The empty amount on row 3 is a null, not a zero. Reading it as 0 would be a
	// silently wrong number in every aggregate downstream.
	if _, ok, err := df.At[float64](2, "amount"); err != nil {
		t.Fatal(err)
	} else if ok {
		t.Errorf("an empty numeric field must be null, not 0:\n%s", df)
	}
}

// TestScanCSVEmptyStringIsNotNull is the other half of the same decision. For a
// String column "" is a value; conflating it with null would be unrecoverable.
func TestScanCSVEmptyStringIsNotNull(t *testing.T) {
	path := writeFile(t, "s.csv", "a,b\n,x\n")
	df, err := ursus.ScanCSV(path).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	v, ok, err := df.At[string](0, "a")
	if err != nil {
		t.Fatal(err)
	}
	if !ok || v != "" {
		t.Errorf("empty String field = (%q, valid %v), want (\"\", true)", v, ok)
	}
}

// TestScanCSVProjectionSkipsParsing is the point of pushing projection into a
// reader. The unselected column is deliberately unparseable as its inferred type:
// if the reader were parsing every column, this query would fail.
func TestScanCSVProjectionSkipsParsing(t *testing.T) {
	// `n` infers as Int64 from the sample, then row 3 holds a word. Selecting only
	// `keep` must succeed; selecting `n` must fail.
	content := "keep,n\na,1\nb,2\nc,not-a-number\n"
	path := writeFile(t, "p.csv", content)

	df, err := ursus.ScanCSV(path, ursus.WithInferRows(2)).
		Select(ursus.Col("keep")).
		Collect(t.Context(), ursus.WithVerify())
	if err != nil {
		t.Fatalf("the unselected column must never be parsed: %v", err)
	}
	if df.Height() != 3 || df.Width() != 1 {
		t.Errorf("got %dx%d, want 3x1\n%s", df.Height(), df.Width(), df)
	}

	if _, err := ursus.ScanCSV(path, ursus.WithInferRows(2)).
		Select(ursus.Col("n")).Collect(t.Context()); err == nil {
		t.Error("selecting the bad column should fail; otherwise this test proves nothing")
	}
}

// TestScanCSVValueErrorQuality pins the error contract. A dataframe library is
// used interactively, and "cannot parse int" on a ten-million-row file is useless.
func TestScanCSVValueErrorQuality(t *testing.T) {
	// A quoted field with an embedded newline before the bad row, so the physical
	// line and the logical record deliberately disagree.
	content := "id,n\n\"a\nb\",1\nc,oops\n"
	path := writeFile(t, "bad.csv", content)

	_, err := ursus.ScanCSV(path, ursus.WithInferRows(1)).Collect(t.Context())
	if err == nil {
		t.Fatal("expected a parse error")
	}
	msg := err.Error()

	for _, want := range []string{
		`"n"`,     // the column BY NAME
		`"oops"`,  // the text found
		"Int64",   // the type expected
		"row 2",   // the DATA row, which is the position in the frame
		"line 4",  // the physical line, which differs from the row
		"bad.csv", // which file
	} {
		if !strings.Contains(msg, want) {
			t.Errorf("error should mention %s:\n%v", want, err)
		}
	}
	if !errors.Is(err, uerr.ErrValue) {
		t.Errorf("kind should be Value: %v", err)
	}
	if errors.Is(err, uerr.ErrInternal) {
		t.Errorf("malformed input is not an ursus bug; the message would send the "+
			"user to the issue tracker over a stray comma:\n%v", err)
	}
}

// TestScanCSVOptions covers the knobs that exist because real files have banners,
// comments, semicolons and sentinel nulls.
func TestScanCSVOptions(t *testing.T) {
	content := "# generated by something\n" +
		"a;b\n" +
		"# a comment in the middle\n" +
		"1;x\n" +
		"2;NA\n"
	path := writeFile(t, "o.csv", content)

	df, err := ursus.ScanCSV(path,
		ursus.WithSeparator(';'),
		ursus.WithComment("#"),
		ursus.WithNullValues("NA"),
	).Collect(t.Context(), ursus.WithVerify())
	if err != nil {
		t.Fatal(err)
	}
	if df.Height() != 2 {
		t.Fatalf("got %d rows, want 2\n%s", df.Height(), df)
	}
	if _, ok, err := df.At[string](1, "b"); err != nil {
		t.Fatal(err)
	} else if ok {
		t.Errorf("NA should have been read as null:\n%s", df)
	}
}

func TestScanCSVNoHeader(t *testing.T) {
	path := writeFile(t, "nh.csv", "1,2\n3,4\n")

	df, err := ursus.ScanCSV(path, ursus.WithHasHeader(false)).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if got := df.Columns(); got[0] != "column_1" || got[1] != "column_2" {
		t.Errorf("default names = %v, want [column_1 column_2]", got)
	}

	named, err := ursus.ScanCSV(path,
		ursus.WithHasHeader(false), ursus.WithColumnNames("x", "y")).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if got := named.Columns(); got[0] != "x" || got[1] != "y" {
		t.Errorf("names = %v, want [x y]", got)
	}
}

// TestScanCSVRaggedLines: a changed field count usually means the file is not what
// the reader thinks it is, so it is an error unless asked for.
func TestScanCSVRaggedLines(t *testing.T) {
	path := writeFile(t, "r.csv", "a,b,c\n1,2,3\n4,5\n")

	_, err := ursus.ScanCSV(path).Collect(t.Context())
	if err == nil {
		t.Fatal("a short record should be an error by default")
	}
	if !strings.Contains(err.Error(), "3 fields") && !strings.Contains(err.Error(), "2 fields") {
		t.Errorf("the error should name both counts: %v", err)
	}

	df, err := ursus.ScanCSV(path, ursus.WithTruncateRaggedLines(true)).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if df.Height() != 2 {
		t.Fatalf("got %d rows, want 2\n%s", df.Height(), df)
	}
	if _, ok, err := df.At[int64](1, "c"); err != nil {
		t.Fatal(err)
	} else if ok {
		t.Errorf("the missing field should be null:\n%s", df)
	}
}

// TestScanCSVLimitStopsReading is what makes Head(10) on a large file fast. The
// tail of the file is unparseable, so a reader that read past the limit would fail.
func TestScanCSVLimitStopsReading(t *testing.T) {
	var b strings.Builder
	b.WriteString("n\n")
	for i := range 100 {
		b.WriteString(strconv.Itoa(i) + "\n")
	}
	b.WriteString("this-is-not-a-number\n")
	path := writeFile(t, "big.csv", b.String())

	df, err := ursus.ScanCSV(path, ursus.WithInferRows(5)).
		Head(10).
		Collect(t.Context(), ursus.WithVerify())
	if err != nil {
		t.Fatalf("Head(10) must stop before the unreadable tail: %v", err)
	}
	if df.Height() != 10 {
		t.Errorf("got %d rows, want 10\n%s", df.Height(), df)
	}

	// Without the limit the same file fails, which is what makes the assertion above
	// evidence of early stopping rather than of a lucky batch boundary.
	if _, err := ursus.ScanCSV(path, ursus.WithInferRows(5)).Collect(t.Context()); err == nil {
		t.Error("the full scan should fail on the bad tail")
	}
}

// TestScanCSVBatchSizeInvariance: batch size is a tuning knob, never a semantic
// one. The same query must give the same answer at every size, including sizes
// that split the file oddly.
func TestScanCSVBatchSizeInvariance(t *testing.T) {
	path := writeFile(t, "sales.csv", salesCSV)

	var want *ursus.DataFrame
	for _, size := range []int{1, 2, 3, 4, 5, 1024} {
		df, err := ursus.ScanCSV(path).
			Sort(ursus.Asc(ursus.Col("qty"))).
			Collect(t.Context(), ursus.WithBatchSize(size), ursus.WithVerify())
		if err != nil {
			t.Fatalf("batch size %d: %v", size, err)
		}
		if want == nil {
			want = df
			continue
		}
		ursustest.AssertFrameEqual(t, df, want)
	}
}

// TestScanCSVMultipleFiles: parts are separate STREAMS, so each header is skipped.
// Concatenating the bytes would make every header after the first a data row.
func TestScanCSVMultipleFiles(t *testing.T) {
	dir := t.TempDir()
	for i, body := range []string{"n\n1\n2\n", "n\n3\n", "n\n4\n5\n"} {
		p := filepath.Join(dir, "part-"+strconv.Itoa(i)+".csv")
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	df, err := ursus.ScanCSVGlob(filepath.Join(dir, "part-*.csv")).
		Collect(t.Context(), ursus.WithVerify())
	if err != nil {
		t.Fatal(err)
	}
	if df.Height() != 5 {
		t.Fatalf("got %d rows, want 5 — a repeated header would be a parse error "+
			"and a lost header a missing row\n%s", df.Height(), df)
	}
	// Glob results are sorted, so the order is the one the names imply.
	for i := range 5 {
		v, _, err := df.At[int64](i, "n")
		if err != nil {
			t.Fatal(err)
		}
		if v != int64(i+1) {
			t.Errorf("row %d = %d, want %d — parts must read in name order\n%s",
				i, v, i+1, df)
		}
	}
}

// TestCSVRoundTrip is the strongest correctness check available for a reader:
// write a frame, read it back, and require it to be identical.
func TestCSVRoundTrip(t *testing.T) {
	src := ursus.Frame(
		ursus.Values("s", []string{"plain", "with,comma", `with"quote`, "with\nnewline"}),
		ursus.Values("i", []int64{1, -2, 0, 9223372036854775807}),
		ursus.ValuesNullable("f", []float64{1.5, 0, -0.25, 0}, []bool{true, false, true, false}),
		ursus.Values("b", []bool{true, false, true, false}),
	)
	want, err := src.Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(t.TempDir(), "rt.csv")
	if err := src.SinkCSV(t.Context(), path); err != nil {
		t.Fatal(err)
	}

	got, err := ursus.ScanCSV(path, ursus.WithSchema(want.Schema())).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if got.String() != want.String() {
		raw, _ := os.ReadFile(path)
		t.Errorf("round trip changed the data\ngot:\n%s\nwant:\n%s\nfile:\n%s",
			got, want, raw)
	}
}

// TestCSVRoundTripNullStrings covers the one thing CSV cannot express by default.
// "" and NULL are the same four columns of nothing, so preserving the difference
// needs a sentinel on BOTH sides — and the default losing it is a property of the
// format, not a defect to be hidden.
func TestCSVRoundTripNullStrings(t *testing.T) {
	src := ursus.Frame(
		ursus.ValuesNullable("s", []string{"a", "", ""}, []bool{true, true, false}),
	)
	want, err := src.Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "ns.csv")

	// Default: the null and the empty string come back identical.
	if err := src.SinkCSV(t.Context(), path); err != nil {
		t.Fatal(err)
	}
	lossy, err := ursus.ScanCSV(path, ursus.WithSchema(want.Schema())).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if lossy.String() == want.String() {
		t.Error("without a sentinel, null and \"\" must be indistinguishable; " +
			"if this passes the documented limitation is wrong")
	}

	// With a sentinel on both sides, the round trip is exact.
	if err := src.SinkCSV(t.Context(), path, ursus.WithNullValue(`\N`)); err != nil {
		t.Fatal(err)
	}
	got, err := ursus.ScanCSV(path,
		ursus.WithSchema(want.Schema()), ursus.WithNullValues(`\N`)).Collect(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if got.String() != want.String() {
		t.Errorf("round trip with a sentinel should be exact\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// TestSinkCSVIsAtomic: a query that fails partway must not leave a truncated file
// where a complete one is expected.
func TestSinkCSVIsAtomic(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.csv")

	// A strict cast that fails partway through, so the sink errors after the
	// header has already been written.
	//
	// This used to use a Datetime column, on the grounds that temporal types were
	// unwritable. Step 6 made them writable, which is a good reason to test
	// atomicity against a FAILING QUERY rather than against whichever types happen
	// to be unsupported this month.
	err := ursus.Frame(ursus.Values("x", []string{"1", "2", "not a number"})).
		Select(ursus.Col("x").Cast(dtype.Int64)).
		SinkCSV(t.Context(), path)
	if err == nil {
		t.Fatal("expected the failing cast to fail the sink")
	}
	if _, statErr := os.Stat(path); !os.IsNotExist(statErr) {
		t.Errorf("a failed sink must leave no file at %s", path)
	}
	// And no temporary debris either.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		names := make([]string, len(entries))
		for i, e := range entries {
			names[i] = e.Name()
		}
		t.Errorf("temporary files left behind: %v", names)
	}
}

// TestSinkCSVStreamsWithoutMaterialising: the sink must hold one batch, not the
// result. This is the "larger than RAM" claim for the write half.
func TestSinkCSVStreamsWithoutMaterialising(t *testing.T) {
	const rows = 50_000

	var b strings.Builder
	b.WriteString("n\n")
	for i := range rows {
		b.WriteString(strconv.Itoa(i) + "\n")
	}
	in := writeFile(t, "in.csv", b.String())
	out := filepath.Join(t.TempDir(), "out.csv")

	before := heapInUse()
	if err := ursus.ScanCSV(in).SinkCSV(t.Context(), out, ursus.WithWriteHeader(true)); err != nil {
		t.Fatal(err)
	}
	// Signed: the heap can legitimately END smaller than it started, and unsigned
	// arithmetic turns that into 1.8e19 bytes of "growth".
	growth := int64(heapInUse()) - int64(before)

	// One batch of int64 plus buffers is well under a megabyte; the whole result is
	// several. The bound is loose on purpose — this catches "accumulated every
	// batch", not an allocation regression.
	if growth > 8<<20 {
		t.Errorf("heap grew by %d bytes streaming %d rows; the sink is accumulating",
			growth, rows)
	}

	n, err := ursus.ScanCSV(out).Count(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if n != rows {
		t.Errorf("wrote %d rows, want %d", n, rows)
	}
}

// TestScanCSVStringBufferIntegrity targets the reader's string LAYOUT rather than
// its parsing, which is what the rest of this file covers.
//
// stringBuilder accumulates Arrow's offsets and character buffer directly instead
// of building a []string — one heap allocation per value became none, 3.18M per
// scan of the benchmark fixture down to 25K. Three properties of that layout are
// easy to break in ways that yield plausible data rather than an error:
//
//   - offsets are BYTE offsets, so anything rune-aware corrupts multi-byte text;
//   - a null and an empty string both leave the offset unmoved, and only the
//     validity bit separates them, so an offsets slip makes them swap;
//   - the field passed to appendField ALIASES the scanner's buffer, which is
//     reallocated and copied whenever a record outgrows it — scanner.go grows by
//     doubling from 64 KiB. Retaining that slice rather than copying its bytes
//     produces garbage that depends on how large the file happens to be.
func TestScanCSVStringBufferIntegrity(t *testing.T) {
	// Comfortably past the scanner's 64 KiB starting buffer, so reading this value
	// forces several grow-and-copy cycles while the field is being assembled.
	huge := strings.Repeat("xyz", 40_000)

	rows := []struct {
		text string // as written to the file
		want string
		null bool
	}{
		{text: "", want: ""},
		{text: "héllo", want: "héllo"},
		{text: `\N`, null: true}, // between two multi-byte values on purpose
		{text: "日本語", want: "日本語"},
		{text: "🌍🌎", want: "🌍🌎"},
		{text: huge, want: huge},
		{text: "tail", want: "tail"}, // proves the offsets recover after the big one
	}

	var buf strings.Builder
	buf.WriteString("s,n\n")
	for i, r := range rows {
		buf.WriteString(r.text)
		buf.WriteByte(',')
		buf.WriteString(strconv.Itoa(i))
		buf.WriteByte('\n')
	}
	path := writeFile(t, "strings.csv", buf.String())

	schema := ursus.MustSchema(ursus.Of("s", ursus.String), ursus.Of("n", ursus.Int64))

	// Every batch size, because finish reuses both buffers across batches and keeps
	// the leading zero by truncating offsets to [:1]. Truncating to [:0] instead
	// drops it, and every batch after the first is then short by a value.
	for _, size := range []int{1, 2, 7, 1024} {
		df, err := ursus.ScanCSV(path,
			ursus.WithSchema(schema), ursus.WithNullValues(`\N`)).
			Collect(t.Context(), ursus.WithBatchSize(size), ursus.WithVerify())
		if err != nil {
			t.Fatalf("batch size %d: %v", size, err)
		}
		if df.Height() != len(rows) {
			t.Fatalf("batch size %d: got %d rows, want %d", size, df.Height(), len(rows))
		}

		for i, r := range rows {
			got, ok, err := df.At[string](i, "s")
			if err != nil {
				t.Fatal(err)
			}
			if ok == r.null {
				t.Errorf("batch size %d: row %d valid = %v, want %v — a null and an "+
					"empty string differ only in the validity bit", size, i, ok, !r.null)
				continue
			}
			if !r.null && got != r.want {
				t.Errorf("batch size %d: row %d = %s (%d bytes), want %s (%d bytes)",
					size, i, elide(got), len(got), elide(r.want), len(r.want))
			}
		}
	}
}

// elide keeps a failure message readable when the value is 120 KB long.
func elide(s string) string {
	if len(s) <= 40 {
		return strconv.Quote(s)
	}
	return strconv.Quote(s[:20]) + "..." + strconv.Quote(s[len(s)-20:])
}

// TestScanCSVIsLazy: constructing a frame over a missing file must not fail until
// the query runs, or `lf := ScanCSV(path)` would be an I/O call in disguise.
func TestScanCSVIsLazy(t *testing.T) {
	lf := ursus.ScanCSV(filepath.Join(t.TempDir(), "does-not-exist.csv"))
	if lf.Err() != nil {
		t.Fatalf("building the frame must not touch the disk: %v", lf.Err())
	}
	if _, err := lf.Collect(t.Context()); err == nil {
		t.Error("collecting a missing file should fail")
	} else if !errors.Is(err, uerr.ErrIO) {
		t.Errorf("kind should be IO: %v", err)
	}
}

// heapInUse returns live heap bytes after a GC. Used to assert that a streaming
// sink holds one batch rather than the whole result — the claim that makes
// "larger than RAM" more than a slogan.
func heapInUse() uint64 {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m.HeapAlloc
}

// threadCounts are the two reader paths. Step 42 split the record loop in two:
// one thread converts fields inline as it scans, more than one stages the raw
// bytes and converts columns concurrently. Everything below reads the SAME file
// through both and asserts they agree, because a second path that disagrees with
// the first is worse than no second path at all.
var threadCounts = []int{1, 8}

// awkwardCSV is a file built to be hostile to a parallel converter: quoted fields
// holding the delimiter, a newline and an escaped quote, so the physical line and
// the logical record disagree; nulls in a numeric column; and an "ord" column
// carrying the input order so a frame that comes back interleaved is visible
// rather than merely suspected.
func awkwardCSV(rows int) string {
	var b strings.Builder
	b.WriteString("ord,name,amount,qty,flag,note,ratio\n")
	for i := range rows {
		amount := strconv.Itoa(i) + ".5"
		if i%7 == 0 {
			amount = "" // null, in the middle of a numeric column
		}
		name := "n" + strconv.Itoa(i)
		switch i % 5 {
		case 1:
			name = `"a,b"` // the delimiter, quoted
		case 2:
			name = "\"line\none\"" // a newline inside a field
		case 3:
			name = `"say ""hi"""` // an escaped quote
		}
		b.WriteString(strconv.Itoa(i) + "," + name + "," + amount + "," +
			strconv.Itoa(i%1000) + "," + strconv.FormatBool(i%2 == 0) + "," +
			`"note ` + strconv.Itoa(i) + `"` + "," +
			strconv.FormatFloat(float64(i)/3, 'f', 6, 64) + "\n")
	}
	return b.String()
}

// TestScanCSVThreadCountsProduceIdenticalFrames is the load-bearing test of step
// 42. Row order is a CSV's data, and the concurrent path converts columns on
// separate goroutines — an index captured by reference, or results collected as
// they finish, produces a frame of exactly the right shape holding the wrong data.
// AssertFrameEqual checks order, so only a value-by-value comparison catches it.
func TestScanCSVThreadCountsProduceIdenticalFrames(t *testing.T) {
	path := writeFile(t, "awkward.csv", awkwardCSV(2000))

	// A small batch size so the file crosses many batch boundaries: the staged
	// path converts per batch, so one batch would exercise it exactly once.
	serial, err := ursus.ScanCSV(path).
		Collect(t.Context(), ursus.WithThreads(1), ursus.WithBatchSize(64))
	if err != nil {
		t.Fatal(err)
	}
	if serial.Height() != 2000 {
		t.Fatalf("got %d rows, want 2000", serial.Height())
	}

	for _, n := range []int{2, 3, 8, 16} {
		got, err := ursus.ScanCSV(path).
			Collect(t.Context(), ursus.WithThreads(n), ursus.WithBatchSize(64))
		if err != nil {
			t.Fatalf("%d threads: %v", n, err)
		}
		ursustest.AssertFrameEqual(t, got, serial, ursustest.CheckNullability())
	}

	// The ordering column, checked directly rather than only through the frame
	// comparison, so a failure says WHICH row moved.
	for _, i := range []int{0, 1, 63, 64, 65, 1999} {
		v, ok, err := serial.At[int64](i, "ord")
		if err != nil {
			t.Fatal(err)
		}
		if !ok || v != int64(i) {
			t.Errorf("row %d: ord = %v (ok=%v), want %d", i, v, ok, i)
		}
	}
	// And the quoted awkwardness actually survived, so the fixture is testing
	// what it claims to.
	if v, _, err := serial.At[string](2, "name"); err != nil {
		t.Fatal(err)
	} else if v != "line\none" {
		t.Errorf("embedded newline: got %q", v)
	}
	if v, _, err := serial.At[string](3, "name"); err != nil {
		t.Fatal(err)
	} else if v != `say "hi"` {
		t.Errorf("escaped quote: got %q", v)
	}
	if _, ok, err := serial.At[float64](7, "amount"); err != nil {
		t.Fatal(err)
	} else if ok {
		t.Error("the empty numeric field should be null")
	}
}

// TestScanCSVErrorsAreIdenticalAcrossThreads pins the error paths across the
// split. A concurrent converter finds errors in whatever order the goroutines
// finish, so the SAME malformed file must still report the same column and the
// same row every run — otherwise a user chasing a bad file gets a different
// answer each time they run.
func TestScanCSVErrorsAreIdenticalAcrossThreads(t *testing.T) {
	t.Run("ragged", func(t *testing.T) {
		path := writeFile(t, "ragged.csv", "a,b,c\n1,2,3\n4,5\n")
		var msgs []string
		for _, n := range threadCounts {
			_, err := ursus.ScanCSV(path).Collect(t.Context(), ursus.WithThreads(n))
			if err == nil {
				t.Fatalf("%d threads: a short record should be an error", n)
			}
			msgs = append(msgs, err.Error())
		}
		if msgs[0] != msgs[1] {
			t.Errorf("the two paths disagree:\n 1 thread:  %s\n 8 threads: %s", msgs[0], msgs[1])
		}

		// And the recovery option behaves the same on both.
		for _, n := range threadCounts {
			df, err := ursus.ScanCSV(path, ursus.WithTruncateRaggedLines(true)).
				Collect(t.Context(), ursus.WithThreads(n))
			if err != nil {
				t.Fatalf("%d threads: %v", n, err)
			}
			if df.Height() != 2 {
				t.Fatalf("%d threads: got %d rows, want 2\n%s", n, df.Height(), df)
			}
			if _, ok, err := df.At[int64](1, "c"); err != nil {
				t.Fatal(err)
			} else if ok {
				t.Errorf("%d threads: the missing field should be null:\n%s", n, df)
			}
		}
	})

	t.Run("bad value, two columns at once", func(t *testing.T) {
		// TWO bad fields in one record. The concurrent path converts columns on
		// different goroutines, so without an explicit rule the reported column
		// would be whichever goroutine lost the race. The rule is file order, and
		// that is what makes this file report "a" and never "b".
		var b strings.Builder
		b.WriteString("a,b,c\n")
		for i := range 300 {
			b.WriteString(strconv.Itoa(i) + "," + strconv.Itoa(i*2) + ",ok\n")
		}
		b.WriteString("nope,alsonope,ok\n")
		path := writeFile(t, "twobad.csv", b.String())

		var msgs []string
		for _, n := range threadCounts {
			_, err := ursus.ScanCSV(path, ursus.WithInferRows(10)).
				Collect(t.Context(), ursus.WithThreads(n), ursus.WithBatchSize(64))
			if err == nil {
				t.Fatalf("%d threads: expected a parse error", n)
			}
			if !errors.Is(err, uerr.ErrValue) {
				t.Errorf("%d threads: kind should be Value: %v", n, err)
			}
			if !strings.Contains(err.Error(), `"a"`) {
				t.Errorf("%d threads: should name the FIRST bad column in file order: %v", n, err)
			}
			if strings.Contains(err.Error(), `"b"`) {
				t.Errorf("%d threads: named the second bad column, so the choice is racy: %v", n, err)
			}
			// Rows are 1-indexed, so 300 good rows put the bad one at 301.
			if !strings.Contains(err.Error(), "row 301") {
				t.Errorf("%d threads: should name the data row: %v", n, err)
			}
			msgs = append(msgs, err.Error())
		}
		if msgs[0] != msgs[1] {
			t.Errorf("the two paths disagree:\n 1 thread:  %s\n 8 threads: %s", msgs[0], msgs[1])
		}
	})

	t.Run("bad values on different rows", func(t *testing.T) {
		// The case that caught step 42's real defect. The serial path converts row
		// by row, so it stops at the earliest bad ROW; the first parallel version
		// reported the earliest bad COLUMN, and this file makes those two answers
		// different — column "b" fails on row 11, column "a" on row 251. The same
		// file then reported a different error depending on how many threads the
		// query happened to be running on.
		var b strings.Builder
		b.WriteString("a,b,c\n")
		for i := range 300 {
			av, bv := strconv.Itoa(i), strconv.Itoa(i*2)
			if i == 10 {
				bv = "badB" // later column, earlier row
			}
			if i == 250 {
				av = "badA" // earlier column, later row
			}
			b.WriteString(av + "," + bv + ",ok\n")
		}
		path := writeFile(t, "cross.csv", b.String())

		var msgs []string
		for _, n := range threadCounts {
			_, err := ursus.ScanCSV(path, ursus.WithInferRows(5)).
				Collect(t.Context(), ursus.WithThreads(n), ursus.WithBatchSize(512))
			if err == nil {
				t.Fatalf("%d threads: expected a parse error", n)
			}
			if !strings.Contains(err.Error(), "row 11") || !strings.Contains(err.Error(), `"b"`) {
				t.Errorf("%d threads: should stop at the earliest bad ROW (row 11, column b): %v", n, err)
			}
			msgs = append(msgs, err.Error())
		}
		if msgs[0] != msgs[1] {
			t.Errorf("the two paths disagree:\n 1 thread:  %s\n 8 threads: %s", msgs[0], msgs[1])
		}
	})
}

// TestScanCSVDegenerateShapesAcrossThreads covers the boundaries every CSV parser
// gets wrong once, on both paths: a last line with no newline after it, a file
// that is only a header, and a file with nothing in it.
func TestScanCSVDegenerateShapesAcrossThreads(t *testing.T) {
	cases := []struct {
		name    string
		content string
		rows    int
		cols    int
	}{
		{"no trailing newline", "a,b\n1,x\n2,y", 2, 2},
		{"header only", "a,b\n", 0, 2},
		{"header only, no newline", "a,b", 0, 2},
		// A file with no header at all is rejected while reading the schema,
		// before either record path runs, so it is not a case this split can
		// change — it has its own sub-test below.
		{"one row, no newline", "a,b\n1,x", 1, 2},
		{"trailing blank line", "a,b\n1,x\n\n", 1, 2},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := writeFile(t, "d.csv", tc.content)
			for _, n := range threadCounts {
				df, err := ursus.ScanCSV(path).Collect(t.Context(), ursus.WithThreads(n))
				if err != nil {
					t.Fatalf("%d threads: %v", n, err)
				}
				if df.Height() != tc.rows || df.Width() != tc.cols {
					t.Errorf("%d threads: got %dx%d, want %dx%d\n%s",
						n, df.Height(), df.Width(), tc.rows, tc.cols, df)
				}
			}
		})
	}

	t.Run("empty file", func(t *testing.T) {
		path := writeFile(t, "empty.csv", "")
		var msgs []string
		for _, n := range threadCounts {
			_, err := ursus.ScanCSV(path).Collect(t.Context(), ursus.WithThreads(n))
			if err == nil {
				t.Fatalf("%d threads: an empty file has no header to read", n)
			}
			msgs = append(msgs, err.Error())
		}
		if msgs[0] != msgs[1] {
			t.Errorf("the two paths disagree:\n 1 thread:  %s\n 8 threads: %s", msgs[0], msgs[1])
		}
	})
}

// TestScanCSVThreadsWithProjection is the case the staged path handles
// differently from the serial one: a projection means the reader stages only
// SOME columns, so the stage index and the file index diverge. Getting that
// mapping wrong puts one column's bytes into another column's builder.
func TestScanCSVThreadsWithProjection(t *testing.T) {
	path := writeFile(t, "proj.csv", awkwardCSV(500))

	want, err := ursus.ScanCSV(path).Select(ursus.Col("ratio"), ursus.Col("ord")).
		Collect(t.Context(), ursus.WithThreads(1), ursus.WithBatchSize(64))
	if err != nil {
		t.Fatal(err)
	}
	got, err := ursus.ScanCSV(path).Select(ursus.Col("ratio"), ursus.Col("ord")).
		Collect(t.Context(), ursus.WithThreads(8), ursus.WithBatchSize(64))
	if err != nil {
		t.Fatal(err)
	}
	ursustest.AssertFrameEqual(t, got, want, ursustest.CheckNullability())

	// Assert the values themselves, not only that the two paths agree: two paths
	// that share a mapping bug agree with each other and are both wrong.
	for _, i := range []int{0, 1, 250, 499} {
		v, ok, err := got.At[float64](i, "ratio")
		if err != nil {
			t.Fatal(err)
		}
		// The fixture writes ratio at six decimals, so the expectation has to
		// round-trip the same way rather than use the full-precision quotient.
		wantV, _ := strconv.ParseFloat(strconv.FormatFloat(float64(i)/3, 'f', 6, 64), 64)
		if !ok || v != wantV {
			t.Errorf("row %d: ratio = %v (ok=%v), want %v", i, v, ok, wantV)
		}
	}
}
